### ISSUE TITLE
Sample Project 

### ISSUE THREAD

**Issue by sachinthanapm** [xiazunyang/signalr-lite#1]
Please show how to use this on a sample app. Include test is bit difficult to understand

**Comment by xiazunyang** [comment]
I add an example project here: https://github.com/xiazunyang/signalr-lite/tree/master/example/signalr-lite-demo

**Comment by sachinthanapm** [comment]
Thanks! Btw, signalRHub.connect not found. Am I missing something ?

Edit: Got it, I was still using the 1.0.0 version. Updated to 1.0.1
